### ISSUE TITLE
New version crashes on Iphone

### ISSUE THREAD

**Issue by firefightersam** [merlos/iOS-Open-GPX-Tracker#147]
The new version of the app crashes after setting some POI. After that the app won‘t open again. Only a reinstall lets me open the app again (it crashes then also after a few POI). I use a IPhone 11 latetest IOS. Data stored on my device. GPS always on. 
I use the very handy app to map hydrants for our volunteer fire dept - I would be very happy if you can fix it.

This is my first post at github - hope everything is fine

**Comment by merlos** [comment]
Thanks @firefightersam 

The issue is related with recovering the session from a file that only has waypoints. 

This will be fixed in next release.

In the mean time, to avoid the crash, if you are using a file or recording a session that only has waypoints, just record your position for a few meters (use the button Start tracking / Resume) and save the file again. It will prevent the app to crash.

Thanks again. Juan.
