### ISSUE TITLE
Which Version Xcode for compiling

### ISSUE THREAD

**Issue by rainbat** [merlos/iOS-Open-GPX-Tracker#15]
Hi,

I tried Xcode 7, now Xcode 6.4 ... i always get Swift errors.
What did you use to compile the current GitHub Version ?

Thanks in Advance and best regards,
Dominique

**Comment by Jactari** [comment]
Yes, I had the same problem compiling with latest version of Swift / xcode. I'll add the Swift error messages tomorrow

**Comment by merlos** [comment]
@rainbat could you please try this branch:
https://github.com/merlos/iOS-Open-GPX-Tracker/tree/features/ios9
It should work on XCode 7.0 (7A220)

**Comment by rainbat** [comment]
@merlos it worked like a charm thank you !
- cloned the project with the github client
- switched to branch features/ios9
- manually added the target OpenGpxTracker using edit schemes in xcode
- clean / compile / run in simulator
Thank you ! Perfect !

**Comment by Jactari** [comment]
Hi guys. So far, I haven't succeeded in compiling what I think is the latest source code. This will be due to my complete ignorance re. X-code. I'm desperate to start testing OGT with Openstreetmap and distance calculation which I think is now available with the latest version of code.  My interest is fittness-for-health which is really big in UK. 

I think I have understood the basics of pixel-based tiling used by Openstreetmap. However, I'm led to believe that Applemaps -- which I think OGT currently uses -- is vector based. Is that so?

The issue that concerns me is that the walking/cycling community here needs to plan a route on-line and then follow it / track it off-line. If I've understood Juan correctly, OGT does not use a cache (I'm not sure how that would be possible, however). So will a switch to (pixel-based) Openstreetmap, within OGT, mean that the map that is available off-line at, say zoom 20, is very limited in coverage?  

What is required is for the user to indicate the centre point of a required location (which may not be the current location) and specify the radius (Kms) of map needed at a specified zoom level. The centre point, of course, would be defined by dropping a pin on a map. Then the app would need to save the data required to provide that map, off-line, when needed by the user. Thus to do this, OGT would need to store maps (collections of tiles), as well as tracks. Could OGT achieve that?

It's worth looking at apps that do this, like Viewranger. They have nightmare GUIs which bewilder the community wanting to use gps tracking for leisure. Viewranger requires 53 parameters to be set up. Yet smart code could automatically set almost all of these parameters by analysing tracking data and simple user inputs. Hence the need for OGT. If anyone is interested in building on Juan's great code, I can provide a user-centred, highly-detailed, functional spec and totally intuitive GUI graphics that the non-tech community will love.
