### ISSUE TITLE
All data lost after crash.

### ISSUE THREAD

**Issue by onato** [merlos/iOS-Open-GPX-Tracker#20]
Since the tracked points are only stored in memory, if the app crashes all data is lost. This could also happen if iOS or springboard crashes. 

I would suggest serialising the points in a way that is fast and doesn't suck the users battery. I guess appending each new point to the end of a file would use the least amount of power. We could use our own JSON format or use a GPX format.

I would be happy to help out with the implementation. What do you think?

**Comment by merlos** [comment]
Your are right, at the moment, there is no way to recover the data. 

Regarding your idea... the file would have to somewhat be aware on when there is a new segment (when pause-play is pressed) and be able to differenciate between waypoints and regular tracking points in order to recover the same state.  

The main drawback of your proposal is that it implies creating a parallel data type, probably increasing the time to maintain the app on the future, isn't it?

What about some kind of autosave? For example every x minutes you can create a reserved name file "autosave.gpx". Automatically the app would save current session. On crash it could be able  to recover almost the whole session.

The main problem of this solution may be large files and battery. I'm not aware on battery performance stuff. We can use  instruments for a test, but let's assume that every minute is 10kb of data in memory (instances of the objects)... Then 1 hour = 10kb x 60 min = 600 kb/h. With this numbers, memory consumption of power should not be a problem to worry about. And then the other issue would be performance on saving large temporary files...

**Comment by Zabanya** [comment]
i vote for autosave, i mistakenly swipe up and lost everything, autosave is good idea as for large files i did a city to city travel around 400km and it only took 1mb file. i think it should be ok

**Comment by merlos** [comment]
@Zabanya thanks for the info.

**Comment by huangjimmy** [comment]
I also think that autosave is a must.
I lost more than 100 km tracks yesterday and 30 km track today because of crash.

I am driving a car and using gpx tracker to record tracks in background. I have navigation in foreground and when I switched from navigation to gpx tracker I found that it crashed before and all tracks were lost.

I am doing manual autosave today to make data recovery possible.

**Comment by vincentneo** [comment]
I have began trialing out crash recovery. Progress can be seen at branch [CrashRecovery](https://github.com/merlos/iOS-Open-GPX-Tracker/tree/crashRecovery), currently as a "proof-of-concept" of how it might work in future. Feel free to try it out. Currently 'simulating' a crash with Xcode stop debugging. (I hope that is actually an accurate crash simulation)

This uses `Core Data` to store trackpoints on the go. Currently, relaunch of app will create a recovery file regardless if previous content is from a crash or not/if there even is any data from core data. In very early stages. Reset of core data content now only done on pressing reset map button. Should be automated once file recovery completes.

Almost everything is done async, should not affect UI at all.

Also, I do not know about the energy impact of this. I have not figured out most of the mechanism, and I expect that it wouldn't be done too quickly either. Any one has any experience with Core Data and its energy usage?

**Comment by merlos** [comment]
Closed in #90
