### ISSUE TITLE
License

### ISSUE THREAD

**Issue by onato** [merlos/iOS-Open-GPX-Tracker#22]
Would you consider using a more liberal license like MIT? 

As far as I know GPL is not compatible with the App Store and that if Apple is aware of this they will reject the app.

**Comment by merlos** [comment]
The source code is GPL'd, but on the App Store I published it under its standard license. I'm not a lawyer, but I guess that the author can set a double license.

Anyway, the main aim to released the source code under GPL is because I wanted any improvement over the code to be available to the community.

**Comment by onato** [comment]
Being GPL means that I can't use the code in my apps. This is a big turn off for supporting the project.

**Comment by chrisjf** [comment]
MIT or Apache would be a great choice of license, rather than GPL!

**Comment by doedje** [comment]
I completely stand behind GPL! It's a solid license that protects the freedom of your code. None of the code can be used in any closed source project (which are mostly commercial). Some people just like to share and contribute to something without a direct benefit for themselves. Just because it is fun to build stuff together. Besides that I think it is quite impossible to change the license of a GPL project. Once GPL means GPL forever. Which is exactly the whole point behind the license in the first place....

**Comment by chrisjf** [comment]
@doedje I too completely stand behind the GPL! It's a good license. It's just unfortunate that The Big Fruit Company (wink wink nudge nudge) is rather anti-GPL these days. :/ Open source licenses can be quite complex beasts, so it's common for there to be confusion and misconceptions around changing licenses, etc. In actuality, a project can be converted from GPL to a lesser copyleft license, as long as all contributors agree. https://opensource.stackexchange.com/questions/33/how-can-a-project-be-relicensed

**Comment by doedje** [comment]
I think there are two sides to this issue:

1) GPL might not be compatible with Apple's App Store.
2) GPL doesn't allow people to use "the code in my apps".

There is a long debate on the first issue on the internet, I won't go into this too deep, I am not a lawyer. Although I do understand that there is nothing in the Apple licenses that does exclude GPL, it's GPL that does have a problem with Apple's licenses. A problem that might be overcome when all contributors agree that it's okay that the Apple licenses throw up some restrictions that are not allowed by the GPL license.... One could still say, "here, look, I have bought this awesome app in the appStore, but look, when you don't like the restrictions Apple throws at you, you could also just download the source here and sideload it from there...."

The second issue is people saying that the GPL license is not really motivating them to contribute because now they can't use any of the code for their own projects. Which is, imho, a bit of a non-argument. If you don't agree with the license, don't contribute to the code, it's that simple...

The last point I want to put forward is that I am pretty much in awe to see that people go that far to put on pressure on a developer to have them change the license for their own benefits (what else?). Merlos chose GPL and for a reason. I back Merlos for that choice! It's a good one! It makes me want to contribute! When GPL is not an option for you, as far as I'm concerned (let me stress out that I am putting forward my own opinion and that I am not talking on Merlos' behalve) take your computing elsewhere...
