### ISSUE TITLE
Possible track duplication when generating gpx file

### ISSUE THREAD

**Issue by vincentneo** [merlos/iOS-Open-GPX-Tracker#75]
Currently cannot determine if it is from this app or CoreGPX library.

In the two cases of files given by @huangjimmy , the smaller file had track duplication, resulting in two tracks of same timestamp.

The larger file (19MB) has quite a few more duplications. track is duplicated 6 times.

From #68

**Comment by vincentneo** [comment]
Analysing the 19MB gpx file seem to show that some tracks may have the same starting trackpoint, but different ending trackpoint.

**Comment by huangjimmy** [comment]
I recorded a 600km/7h35:51 gpx with latest GPX Tracker v1.6 today, the file size is over 40MB.
The correct distance is 580km, after loading the gpx again, it shows that total distance is 7329km.

I often saved tracks to file because I was afraid it might crash and all my data were lost.

The first 9 tracks are identical, i.e., the same track is repeated 9 times.

Other 10 tracks are identical too, but they include the content of previous 9 tracks.

Because this file contains some privacy data that may reveal my home address, I will not upload the gpx file for analysis.

I believe the description above does provide some hint about this bug.

**Comment by vincentneo** [comment]
@huangjimmy Thank you for testing the app again.

I understand that the file would contain privacy stuff, and analysing it can't do much anyway.

> I often saved tracks to file because I was afraid it might crash and all my data were lost.

I am guessing that it might be possible that the issue has to do with this.
Normally, when saved, the file isn't overwritten, only appended. Any newer content is added as a new track. I believe this issue is with the fact that when saved, the already saved data is not cleared in memory. 

Before saving, the distance will always be 'correct' as it is reading directly from memory. When viewing the saved one, the parser will parse the file and calculate all distances from the parsed track points (when duplicated, distance calculation is also duplicated, in a sense.)

I think it should be fixable. But I am unsure if it will impact performance when saving. I will do some testing when free, on the saving mechanism, and I will update you on this issue as soon as I get around it.

**Comment by vincentneo** [comment]
Have done a brief test, and indeed the cause is due to saving the file multiple times.

**Comment by huangjimmy** [comment]
I think the problem is in GPXMapView.swift exportToGPXString method.

Suppose I never pause tracking, there will be only one trackSegment, i.e. the  trackSegment represented by self.currentSegment and there is zero element in self.tracks.

First time I tap Save, self.tracks will be an array with one element (one track containing one segment).

Second time I tap Save again, If there is no new coordinates recorded, self.tracks will be an array with two tracks where both tracks are identical.

If I first "Pause", then "Save", finally "Resume", empty track segments will be recorded if there are no new GPS coordinates generated.

The member variable self.tracks can only be 
1 cleared in clearMap method by 'self.tracks = []'
2 append in exportToGPXString 'self.tracks.append(track)'
3 assigned in importFrom GPXRoot 'self.tracks = gpx.tracks'

`
  func exportToGPXString() -> String {
        print("Exporting map data into GPX String")
        //Create the gpx structure
        let gpx = GPXRoot(creator: kGPXCreatorString)
        gpx.add(waypoints: self.waypoints)
        let track = GPXTrack()
        track.add(trackSegments: self.trackSegments)
        //add current segment if not empty
        if self.currentSegment.trackpoints.count > 0 {
            track.add(trackSegment: self.currentSegment)
        }
        self.tracks.append(track)
        gpx.add(tracks: self.tracks)
        return gpx.gpx()
    }
`

**Comment by vincentneo** [comment]
With your comment, I think I misunderstood the code before...
I will try again now on the `exportToGPXString` part.

**Comment by vincentneo** [comment]
Yet to test latest commit, will test tmr.

**Comment by vincentneo** [comment]
Additional commits from Branch [savingFix](https://github.com/merlos/iOS-Open-GPX-Tracker/tree/savingFix) should fix the issue.

@huangjimmy if you could side load the app from that branch and test it out, and it works, I will do a pull request.

Personal testing seems to show that tracks are no longer duplicated.

**Comment by huangjimmy** [comment]
I will do some thorough test on Sunday. 
I did test saveFix branch and it seemed to work, but I was not so sure because the test was just a few kilometers long.

**Comment by merlos** [comment]
Hi both!

Thank you very much for the research you did! Thanks to that I was able to find a simple fix quickly.

@vincentneo I made a pull request that should fix the issue. Please, check the notes.

**Comment by huangjimmy** [comment]
> I will do some thorough test on Sunday.
> I did test saveFix branch and it seemed to work, but I was not so sure because the test was just a few kilometers long.

I've tested the new version and compared it with v1.6.0.

The track recorded during test was 12.95 kms.

The old 1.6.0 version recorded several duplicate tracks while the new one did not produce any duplicates.

**Comment by merlos** [comment]
I've just uploaded 1.6.1 (https://github.com/merlos/iOS-Open-GPX-Tracker/milestone/6) to the App Store that includes this fix. Once Apple finishes the review, the new version will be available for download.

 謝謝 @huangjimmy
