### ISSUE TITLE
Add distance as measure

### ISSUE THREAD

**Issue by merlos** [merlos/iOS-Open-GPX-Tracker#8]
Add the distance of the current track.
Use meters till 1k and then set km with two decimals (ie: 1.12 km)

**Comment by Jactari** [comment]
Yes this is a key requirement. For clarity / legibility, on a small screen, I suggest ONLY distance and elapsed time (hours : minutes * are presented at the top of the screen white out of a black bar.
This raises some GUI issues / opportunities which I'll cover separately.

An extension of the distance function is listing track duration and distance against each name in the file list.

And yet another development would be if distance could be calculated between pins that the user has added to, say, a blank map. In this way, a route could be planned -- in terms of track to be taken and distance. The positioning of pins is of course an existing, elegant function.

* Meaning no seconds / no decimals of minutes – to save screen real estate. What's everyone's view on this, given the app is likely to be used for tracking rather than measuring short duration events?
