### ISSUE TITLE
Map not centred on location, on start up

### ISSUE THREAD

**Issue by Jactari** [merlos/iOS-Open-GPX-Tracker#9]
As I recall, at my first use of the app, the map presented located instantly on the current location. Now the start mode is a location in the middle of the ocean! To get the map centred on the location takes two presses of the dart symbol. No big deal but confusing for a new user.

**Comment by merlos** [comment]
By default the iOS GPS sets user coords in (0,0) which is in the middle of the ocean, but because it takes some time to 

The solution I guess may improve this issue is to center the map on the last known position when opening. Also, check if there something provided by the system to avoid this 0,0 default.

**Comment by Jactari** [comment]
Hi Juan,

Thanks for the explannations. I mentioned some small issues that I came across. They are not a priority.

Dare I ask, did you manage to compile the code and make the change to utilise Openstreetmap?

Did you like the sample opening graphic I sent? It originates as a vector file and will be modified to suit the required aspect ratio/s.

I have a number of GUI suggestions which are for the future. For these mods, I am creating vector files of suggested symbols.

Thanks

David

**Comment by merlos** [comment]
1.2 includes this feature.
