### ISSUE TITLE
Map caching may fail to work unexpectedly on certain tiles

### ISSUE THREAD

**Issue by F3000** [merlos/iOS-Open-GPX-Tracker#96]
Hi, 

I open the app with internet connection and download a area. Hard close the app the turn on flight mode. Open the app and I can’t see any map tiles . 

Have I made something wrong ?

**Comment by vincentneo** [comment]
I have preliminarily tested this and have identified it as a possible bug. I noticed that some tiles were not properly cached. 

With that said, you should still be able to see selected tiles after caching. Maybe try closing it first, then force close?

**Comment by F3000** [comment]
I have tried that . I see after normal close only the tile where my position is. After hard close the cashed ones are gone . 

Maybe you implement a permanent offline usage possibility.

**Comment by vincentneo** [comment]
Indeed the caching system should be improved, as it seems quite unstable right now. Sometimes it works, sometimes it doesn't, and the clear cache functionality, noted in #74 doesn't work too.

**Comment by F3000** [comment]
Does the main developer of the App also work on the App ?

**Comment by merlos** [comment]
@F3000 Yes, whenever I have some spare time... 

You can also work on the app. Just clone the the repo, add your changes and make a pull request, like @vincentneo has fantastically being doing for the last months.

Regarding the issue, it is related with the Cache pod. A while ago this library was overhauled with a focus on other use cases. Since then it is not working as it used to do. 

The ideal solution would be to use a much more simple and focused cache library focused on maps that could also be the foundation to support offline maps. As far as we know, there is no open source library that supports these features.

This is something that has already been discussed with @vincentneo in https://github.com/merlos/iOS-Open-GPX-Tracker/pull/63#issuecomment-466779892

**Comment by merlos** [comment]
I have been working on a separate project to create a specialized cache for mapping apps.

https://github.com/merlos/MapCache

I still need to implement a expiration mechanism. Once I finish that, I will integrate it with Open GPX Tracker.
